language: python
python:
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev

install:
  - pip install codecov
  - python setup.py install
script:
  - coverage run test/factory.py

after_success:
  - codecov
